FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN \
 apt-get update && \
 apt-get install -y \
      build-essential \
      python3-pip \
      python3-setuptools

RUN pip3 install ansible

COPY . /ansible

RUN \
 echo "**** running ansible ****" && \
 cd /ansible && \
 ansible-playbook -i localhost bench.yml
